# Generated by Django 5.1.7 on 2025-03-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maldives_eats', '0003_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.TextField(default='', max_length=100),
        ),
    ]
